### ISSUE TITLE
validation3.js / Prado.WebUI.TActiveCustomValidator

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#542]
Hi,

In the function validate (line 1580), this function return always true in the line 1600 even if the parameter of the control isValid equal false. Why she does not return this.isValid ?

validate : function(invoker)
	{
		this.invoker = invoker;

		//try to find the control.
		if(!this.control)
			this.control = jQuery("#" + this.options.ControlToValidate).get(0);

		if(!this.control || this.control.disabled)
		{
			this.isValid = true;
			return this.isValid;
		}

		if(typeof(this.options.OnValidate) == "function")
		{
			if(this.requestDispatched == false)
				this.options.OnValidate(this, invoker);
		}

		return true;
	},

**Comment by ctrlaltca** [comment]
That code handles the validation of TActiveCustomValidator. When the value of the control TActiveCustomValidator is attached to changes, TActiveCustomValidator will make an ajax request. We'll have to wait for the ajax response to understand wether the validation has succeeded or not.
I think you have a good point; if the validation has failed before, returning true instead of this.isValid we'll reset the validator in a wrong state until the callback has returned with the correct value.

**Comment by majuca** [comment]
doest it means that you will change it?

**Comment by ctrlaltca** [comment]
I'll have a look at it once i'll test validators. Currently i'm developing a quite large change on the php part.

**Comment by ctrlaltca** [comment]
Fixed in #553
