### ISSUE TITLE
Prado CHM help file not available anymore

### ISSUE THREAD

**Issue by gnits** [pradosoft/prado#547]
The framework documentation in .chm help file format is not available anymore at http://www.pradosoft.com/download/, neither as part of the source distribution, nor as a separate download.

The last distribution that included the .chm file was v3.2.2 (as part of the documentation download package), but the file is not present in the unified download packages since v3.2.3. As far as I can tell there are also no build instructions/script on how to create your own one.

**Comment by ctrlaltca** [comment]
Yep, the creation of the CHM file has been removed from the build scripts. CHM is an old, insecure format that's not supported anymore by MS itself since Windows Vista.

**Comment by gnits** [comment]
That would be funny, because even Windows 8.1 has its help files in the .chm format. You're probably referring to the .hlp format instead, which is indeed not supported since Vista by default (even though MS offers the .hlp reader as an optional download), but which wasn't removed either, because it was insecure, but because it was simply outdated feature-wise.

The point is: .chm is neither insecure, not unsupported. And without that, there's no reference documentation available for Prado which would be easily searchable. The plain vanilla HTML and PDF versions of the documentation are not indexed (and the HTML version is PITA to handle because of the bazillion files anyway).

So what are the real arguments against the inclusion of the .chm file, and if there aren't any, when will it be brought back?

**Comment by ctrlaltca** [comment]
FYI, "Microsoft Compiled HTML Help" (aka CHM) has been replaced since 2001 by "Microsoft Help 2" (aka HxS), and again by "Microsoft Help Viewer" in 2010, but this is not the point.
Then, if microsoft itself is still deploying its help files in an old format, i'm not really interested.
Anyway, CHM are considered insecure (try to open a CHM from a network path, or just goole for "chm code execution"), but this is not the point, again.
In order to create Prado's CHM documentation you need to run a "compiler" (that can be downloaded here: http://www.microsoft.com/en-us/download/details.aspx?id=21138) that runs only under windows, and never got really implemented inside the build scripts. 

```
There's no reference documentation available for Prado which would be easily searchable at various levels
```
This is a good point, that surely needs a proper fix.
Anyway, i don't plan of manually generating CHM files myself anymore, but if someone is up for the task i'll be glad to publish them or incorporate a PR that handles this.

**Comment by ctrlaltca** [comment]
The CHM help will not be included anymore. It contained the same very same content of the pdf (still shipped with new versions) and the quickstart demo. The quickstart demo implements the "search" functionality.
