### ISSUE TITLE
TActiveFileUpload does not work inside TJuiDialog

### ISSUE THREAD

**Issue by szroman** [pradosoft/prado#607]
Hi,

Example:

```php
class Test extends TPage
{
    public function onInit($param)
    {
        parent::onInit($param);

        $this->FileUpload->OnFileUpload[] = array($this, 'FileUploaded');
    }

    public function FileUploaded($sender, $param)
	{
        $this->Description->Text = '';

        if ($sender->HasFile)
        {
            $this->Description->Text = $sender->FileName;
        }
    }
}
```

```html
<com:TContent ID="Main">

<com:TJuiDialog
    Options.Modal="true"
    Options.Width="auto"
    Options.AutoOpen="True">

    <com:TActiveFileUpload ID="FileUpload" />
    <com:TActiveLabel ID="Description"  />

</com:TJuiDialog>

</com:TContent>
```

**Comment by ctrlaltca** [comment]
Hi, this problems is similar to #588; the problem is caused by TJuiDialog removing its inner elements from the form, so that they doesn't get sent as they should. #593 fixes the problem for ajax callbacks, but file uploads works using a normal postback so they're currently broken.
I'm trying to implement a patch to fix this.

**Comment by szroman** [comment]
Hi, thanks for your response. Just let me know when you finish, please. Another thing with TActiveFileUpload is that it does not work without cache being enabled in appliaction.xml. Would be nice to put this information into documention. It took me few hours to figure it out.

**Comment by szroman** [comment]
I have applied your patch and it seems to work fine. Thanks again.
