### ISSUE TITLE
Form no longer shows if there is no redirection

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#608]
Hello
When i provide wrong parameters for login, the return is the same login page without form. Working well on 3.2.4 but not on 3.3.1
[login.zip](https://github.com/pradosoft/prado/files/429839/login.zip)

**Comment by ctrlaltca** [comment]
Since PRADO 3.3.0, jQuery is the javascript framework of choice. All the existing PRADO controls have already been ported, and prototype is still included to provide backward compatibility for custom controls.
Anyway, updating custom controls is probably a good idea. Have a look at the "[Upgrading from v3.2](http://pradoframework.net/demos/quickstart/?page=GettingStarted.Upgrading32)" page in the Quickstart tutorial for more informations.

I advice you to add a TJavascriptLogger on your page or to look in the browser's development tools for javascript errors and fix them.

The page you attached depends on external classes to work (UserRecord, _Tools, Kmail just to name a few), so i'm unable to test it.

**Comment by frkinta** [comment]
Here is more full project for test
[issue.zip](https://github.com/pradosoft/prado/files/429948/issue.zip)

**Comment by ctrlaltca** [comment]
If you want to fix the problems, i'll be glad to assist you, but i won't do your homeworks.
Try to debug the app and once you get the specific problem, feel free to ask.

**Comment by ctrlaltca** [comment]
Looking at the error log:
```
Aug 22 12:55:33 [Error] [System.TApplication] TDbCommand failed to execute the query SQL "SHOW INDEX FROM `avidoc_user`": SQLSTATE[42S02]: Base table or view not found: 1146 Table 'avidoc.avidoc_user' doesn't exist
Aug 22 13:03:32 [Error] [System.TApplication] TDbCommand failed to execute the query SQL "SHOW INDEX FROM `avidoc_user`": SQLSTATE[42S02]: Base table or view not found: 1146 Table 'avidoc.avidoc_user' doesn't exist
```
It seems like you miss some tables in the database.

**Comment by frkinta** [comment]
Many thanks for your answer but after debugging and removing unneccessary code, I believe that the problem exist. 
I have upload a single code and run it with [Prado 324](http://pouola.com/issue/index324.php) and [Prado331](http://pouola.com/issue/index331.php). When you submit, the form don't show again with prado 331.

You can see the page
[login.zip](https://github.com/pradosoft/prado/files/430503/login.zip)
 script and all site script
[issue2.zip](https://github.com/pradosoft/prado/files/430504/issue2.zip)

**Comment by ctrlaltca** [comment]
I've tested the contents the last zips on osx / chrome / php56 / apache24.
I  had to comment some parts of the main `.htaccess` file and of the file in `assets` (about the deflate and index module), but i think that doesn't matter with your issue.

It seems to work for me, here's the result:

![new](https://cloud.githubusercontent.com/assets/1631111/17861318/dbc14b22-6890-11e6-85c2-71fc3dd0b877.gif)

Maybe i'm missing something.. do you get the same result?

**Comment by frkinta** [comment]
I'm getting the same result. Please see the login pages. this is the function executed when submitted:

>     function processLogin($sender, $param) {
        $this->lblResult->Text = 'Please check your parameters';
        if ($this->Page->IsValid) {
            if ($this->txtEmail->SafeText == 'email@email.com' && $this->txtPw->SafeText == 'emailpw') {
                $this->lblResult->Text = 'Well done';
            }
        }
    }


The only thing done after submission is write the result. There is not redirection and the form is not hidden but it don't appear. If you fill and submit this ([prado 324 form](http://pouola.com/issue/index324.php)) exactly like you did with the zipped files, the text result appear and the form too.
When entering wrong or good parameters the html input on the page disappear.

_Excuse my poor english_

**Comment by frkinta** [comment]
this is the acual result
![image](https://cloud.githubusercontent.com/assets/20577647/17863303/093d1324-6891-11e6-8747-12bb3e8a7832.png)

this is how I expect the result to be
![image](https://cloud.githubusercontent.com/assets/20577647/17863324/1cfb3ae4-6891-11e6-8785-54066c29caa8.png)

**Comment by ctrlaltca** [comment]
So, i finally understood the issue and committed a fix for it.
Long story: when a viewstate value (like the TPanel's Visible property, in this case) was set to a value from inside a template (Visible=false) and then reset to its default value from php code (Visible=true), Prado was using the value set from the template instead of the correct value.
Expect a new release 3.3.2 in a short time with the fix.

**Comment by ctrlaltca** [comment]
Release 3.3.2 is out: https://github.com/pradosoft/prado/releases and contains the fix.

**Comment by frkinta** [comment]
Good Job. You've done the homework.
Sorry for the bad way I've explain the issue and thanks for your determination to understand me.
