### ISSUE TITLE
What is the mean 'Unable to alter response as HTTP header already sent'

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#612]
Hello,

My problem is stil same, cannot redirect to other page. i get this error on my log.

```
[Wed Sep 14 03:21:11.209677 2016] [lsapi:error] [pid 408021] [client 202.67.47.20:21469] [host clawb.yacanet.com] Backend fatal error: PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to alter response as HTTP header already sent' in /home/yaca/clawb/framework_332/pradolite.php:3770
Stack trace:
#0 /home/yaca/clawb/framework_332/pradolite.php(613): THttpResponse->setStatusCode(500, NULL)
#1 /home/yaca/clawb/framework_332/pradolite.php(569): TErrorHandler->handleExternalError(500, Object(TPhpErrorException))
#2 /home/yaca/clawb/framework_332/pradolite.php(72): TErrorHandler->handleError(NULL, Object(TPhpErrorException))
#3 /home/yaca/clawb/framework_332/pradolite.php(65): PradoBase::exceptionHandler(Object(TPhpErrorException))
#4 [internal function]: PradoBase::phpFatalErrorHandler()
#5 {main}
  thrown in /home/yaca/clawb/framework_332/pradolite.php on line 3770
, referer: http://clawb.yacanet.com/index.php?page=sa.default.Home
```

I'm found the error message "Unable to alter response as HTTP header already sent" from 'Framework/Web/THttpResponse.php'.

and my question is what is the mean "Unable to alter response as HTTP header already sent" ? and how to fix this situation ?

Specification my system :
1. Cloudlinux OS
2. Web server with Mod_Lsapi
3. PHP 5.6

Thanks...

**Comment by ctrlaltca** [comment]
So, Prado detected a Php fatal error is occurring, and tried to redirect you to the Prado error page with all the informations on the error. Unfortunately this error occurred at runtime after some output had already been sent to the browser, and this is causing yet another error.
The problem here is that instead of getting the details of what's causing the original problem, you are getting the details of the error happening inside Prado.
I'll try to fix the login and avoid the problem.

**Comment by mrizkir** [comment]
i'm switched php version to 5.4 or 5.5. it has worked.
