### ISSUE TITLE
ActiveDropDownList not return the value after disabled=false Prado 3.3.2

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#619]
Hello, i have strange issue in here. ActiveDropDownList not return value after disable release to false by jquery. Here my example code :

```
<com:TActiveDropDownList ID="cmbAddBagian" OnSelectedIndexChanged="changeCMB">
<prop:ClientSide.OnPreDispatch>         
                                Pace.stop();
                                Pace.start();
                                $('#<%=$this->cmbAddBagian->ClientId%>').prop('disabled',true);         
                            </prop:ClientSide.OnPreDispatch>
                            <prop:ClientSide.OnLoading>
                                $('#<%=$this->cmbAddBagian->ClientId%>').prop('disabled',true);                     
                            </prop:ClientSide.OnLoading>
                            <prop:ClientSide.OnComplete>                                                                    
                                $('#<%=$this->cmbAddBagian->ClientId%>').prop('disabled',false);                                                                                                                 
                            </prop:ClientSide.OnComplete>
</com:TActiveDropDownList>
```

I have used code like in 3.2.3, the dropdownlist is looking not disabled when OnLoading.

```
<com:TActiveDropDownList ID="cmbAddBagian" OnSelectedIndexChanged="changeCMB">
<prop:ClientSide.OnPreDispatch>         
                                Pace.stop();
                                Pace.start();
                                $('#<%=$this->cmbAddBagian->ClientId%>').disabled='disabled';         
                            </prop:ClientSide.OnPreDispatch>
                            <prop:ClientSide.OnLoading>
                                $('#<%=$this->cmbAddBagian->ClientId%>').disabled='disabled';                     
                            </prop:ClientSide.OnLoading>
                            <prop:ClientSide.OnComplete>                                                                    
                                $('#<%=$this->cmbAddBagian->ClientId%>').disabled='';                                                                                                                 
                            </prop:ClientSide.OnComplete>
</com:TActiveDropDownList>
```
php code :
```
public function changeCMB ($sender,$param) {
echo $sender->Text;
}
```

**Comment by ctrlaltca** [comment]
It seems to work here with minor changes:
![new](https://cloud.githubusercontent.com/assets/1631111/21231793/d0cf5b92-c2e9-11e6-8cbd-ab5e06ae76a1.gif)

I've only changed the `TActiveDropDownList` to use the `OnCallback` event instead of the `OnSelectedIndexChanged ` event:
```
<com:TActiveDropDownList ID="cmbAddBagian" OnCallback="changeCMB">
``` 
and added a `sleep` in the php code only for testing, to ensure the disabled state is noticeable :
```
public function changeCMB ($sender,$param) {
	sleep(2);
	echo $sender->Text;
}
```

> I have used code like in 3.2.3, the dropdownlist is looking not disabled when OnLoading.
> `$('#<%=$this->cmbAddBagian->ClientId%>').disabled='disabled';`

Prado 3.2 uses prototype.js so you don't need to specify the `#` before the client ID: `$('clientID')`
Prado 3.3 uses jQuery, so the notation is correct: `$('#clientID')`

I-ll investigate the problem on

**Comment by LCSKJ** [comment]
The problem is that all client-side events are raised prior to fetching the form values with getParameters(), which uses jQuery('input, select, textarea').serialize() that is ignoring disabled form elements by default.
Since onPreDispatch is raised very early and onLoading, onLoaded, onInteractive are even just simulated (since they come from Prototype and don't exist in jQuery) right afterwards, disabling form elements within any eventhandler of these events will exclude them from post data.

@ctrlaltca 
We may consider putting
`this.options.data = this.getParameters();`
before or in between these events to allow disabling elements.
What do you think?

**Comment by ctrlaltca** [comment]
I had a look again at the event descriptions: http://pradoframework.net/demos/quickstart/?page=ActiveControls.CallbackClientSide

Having an event triggered after parameters are gathered is useful as you stated.
I'd keep at least one event to trigger before parameters are gathered, so that an user is able to change values on the form just before an ajax call.

So, my proposal is:

```
		// trigger an event before the callback parameters are collected
		if(this.options.onPreDispatch)
			this.options.onPreDispatch(this,null);

		// prepare callback paramters
		this.options.data = this.getParameters();
		this.options.url = this.getCallbackUrl();
		this.options.timeout = this.getRequestTimeOut();

		// jQuery don't have all these states.. simulate them to avoid breaking old scripts
		if (this.options.onLoading)
			this.options.onLoading(this,null);
		if (this.options.onLoaded)
			this.options.onLoaded(this,null);
		if (this.options.onInteractive)
			this.options.onInteractive(this,null);

```

Is this acceptable?

**Comment by LCSKJ** [comment]
Yes, sounds reasonable - between onPreDispatch and onLoading is a good place to gather form values.

**Comment by mrizkir** [comment]
i think my problem is like described by  @LCSKJ. Disabled element will exlcude from post data. so when i changed to OnCallback, the same problem is still exists.
