### ISSUE TITLE
The url tag produce an extra directory separator before the result

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#625]
Hello,

I have a problem using Url Tags When i add `"<%/ image.jpg %>"` I have good result in localhost but on  production server I have a directory separator before the url; resulting `"\/image.jpg"` on IIS

**Comment by ctrlaltca** [comment]
Can you please try to patch `framework/Web/UI/TTemplate.php` [at line 665](https://github.com/pradosoft/prado/blob/prado-3.3/framework/Web/UI/TTemplateManager.php#L665) so that the line reads:

OLD
```php						$tpl[$c++]=array($container,array(TCompositeLiteral::TYPE_EXPRESSION,"rtrim(dirname(\$this->getApplication()->getRequest()->getApplicationUrl()), '/').'/$literal'"));
```

NEW
```php						$tpl[$c++]=array($container,array(TCompositeLiteral::TYPE_EXPRESSION,"rtrim(dirname(\$this->getApplication()->getRequest()->getApplicationUrl()), '/\\').'/$literal'"));
```

If it works, i'll be glad to commit the fix here and in a few other places where the same issue is present in the framework. Thank you

**Comment by frkinta** [comment]
I changed it in `framework/Web/UI/TTemplateManager.php` but it didn't work

**Comment by ctrlaltca** [comment]
So, i took the time of installing a fresh Windows 7 vm, install IIS7.5 with php5.6 (fastcgi) and load up prado and prado-demos.
I've modified the "helloworld" demo like this:
```
<html>

<head>
<title>Hello World Demo - Prado</title>
</head>

<body>

<com:TForm>
<com:TButton Text="Click me" OnClick="buttonClicked" />
<br/>
<com:TImage ImageUrl="<%/ welcome.png %>" />
</com:TForm>

</body>
</html>
```

And here's the result:

![schermata 2016-01-01 alle 15 26 52](https://cloud.githubusercontent.com/assets/1631111/21581568/cae73ee8-d036-11e6-9d88-705e2cf57169.png)

So, it looks that in my test this is working. Can you try to replicate my test and post the result?

**Comment by frkinta** [comment]
Can we consider this information to have a solution?
[http://php.net/manual/fr/function.dirname.php#54868](http://php.net/manual/fr/function.dirname.php#54868)

**Comment by frkinta** [comment]
Another error occured when trying to change the "helloword"

MasterLayout.tpl

```html
<!DOCTYPE html>
<html lang="fr">
    <com:THead Title="Accueil">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="<%/ assets/images/favicon.png %>" rel="icon" type="image/png" />
        <link href="<%/ assets/bootstrap-334/css/bootstrap.min.css %>" rel="stylesheet" type="text/css" />
    </com:THead>
    <body>
    <com:TForm>
        <com:TContentPlaceHolder ID="Main" />
    </com:TForm>
</body>
</html>
```

MasterLayout.php
```php

class MasterLayout extends TTemplateControl {
    public function onLoad($param) {
        parent::onLoad($param);
    }
}

```

helloword2.page
```html
<%@ MasterClass="Application.pages.MasterLayout" %>

<com:TContent ID="Main">
    <com:TButton Text="Click me" OnClick="buttonClicked" />
    <br/>
    <com:TTextBox Text="<%/ logoONAB.jpg %>" Style="width:40em"/>
    <com:TImage ImageUrl="<%/ logoONAB.jpg %>" AlternateText="<%/ logoONAB.jpg %>" />
    <com:TImage ImageUrl="<%/ assets/logoONAB.jpg %>" AlternateText="<%/ assets/logoONAB.jpg %>" />
</com:TContent>
```

The result is an error

![image](https://cloud.githubusercontent.com/assets/20577647/21602293/b0b053b8-d192-11e6-8de7-dd5919900a04.png)

**Comment by frkinta** [comment]
Finally I corrupt TComponent on line 1232

```php
	public function evaluateExpression($expression)
	{
		$expression=$this->dyEvaluateExpressionFilter($expression);
		try
		{
                    $expression=str_replace("rtrim(", "",$expression);
                    $lst = explode('.',$expression);
                    $tmp = explode(',',$lst[0]);
                    $lst[0]=$tmp[0];
                    $expression=implode('.',$lst);
			if(eval("\$result=$expression;")===false)
				throw new Exception('');
                        $result = str_replace('\\','',$result);
			return $result;
		}
		catch(Exception $e)
		{
			throw new TInvalidOperationException('component_expression_invalid',get_class($this),$expression,$e->getMessage());
		}
	}
```
It is solution for the initial problem. I don't know if it have a negative impact elsewhere.

**Comment by ctrlaltca** [comment]
That's more a workaround than a fix, and it will have a negative impact on every expression that contains a '\' character, removing it. A real fix would be to understand what adds the character in the expression in the first place.

**Comment by frkinta** [comment]
So I'm really in trouble

**Comment by frkinta** [comment]
The problem is the return of `dirname` php function.

On server root (windows), 
- `$this->getApplication()->getRequest()->getApplicationUrl()` return `/index.php` or `/helloword/index.php`.
- `dirname($this->getApplication()->getRequest()->getApplicationUrl())` will return`\` or`/helloword` (The `\` prefix only appear when `index.php` is on `$_SERVER["DOCUMENT_ROOT"]`).

`rtrim(dirname($this->getApplication()->getRequest()->getApplicationUrl()), '/').'/logoONAB.jpg'` or `rtrim(dirname($this->getApplication()->getRequest()->getApplicationUrl()), '/\').'/logoONAB.jpg'` always return `\/logoONAB.jpg`.

When I change `rtrim(dirname($this->getApplication()->getRequest()->getApplicationUrl()), '......')` to
`str_replace('\\', '', dirname($this->getApplication()->getRequest()->getApplicationUrl()))` it work both on windows and linux.

**Comment by ctrlaltca** [comment]
Thank you for the update, will test later today

**Comment by LCSKJ** [comment]
This may also be a problem with platform specific DIRECTORY_SEPERATORs ... `dirname()` (normally) works with file paths but in TTemplate it gets passed an URL. Under linux only / (slashes) are valid in file paths and under windows both / (slashes) and \ (backslashes) are valid, but URLs always only contain / (slashes). Now, if your entry script (which `$this->getApplication()->getRequest()->getApplicationUrl()` returns) gets passed to `dirname()` it may return a \ (backslash) if it is top level which will not get trimmed by `rtrim(..., '/')`.

Example:
~~~php
$url = '/index.php';
$dirname = dirname($url);
$trim = rtrim($dirname, '/');
~~~
This will result in `$dirname` containing a / (slash) under linux and a \ (backslash) under windows and thus `$trim` will be empty under linux and contain a \ (backslash) under windows, which is exactly the behavior @frkinta is facing.

So a fix could be to change `framework/Web/UI/TTemplate.php` [at line 665](https://github.com/pradosoft/prado/blob/prado-3.3/framework/Web/UI/TTemplateManager.php#L665)  to use DIRECTORY_SEPERATOR instead of '/' for trimming like
~~~php
$tpl[$c++]=array($container,array(TCompositeLiteral::TYPE_EXPRESSION,"rtrim(dirname(\$this->getApplication()->getRequest()->getApplicationUrl()), DIRECTORY_SEPERATOR).'/$literal'"));
~~~

I do not have a windows server at hand, would be nice if some can test it ... I can guarantee nothing though, it's just a proposal :smile:

**Comment by ctrlaltca** [comment]
So, i finally manager to reproduce the problem and test a fix for it.
The original patch proposed in https://github.com/pradosoft/prado/issues/625#issuecomment-269861486 was working, but we need to patch the code in another point to fix the same issue when the url tag was used inside a component property, eg:
```
<com:TTextBox Text="<%/ image.jpg %>" />
```

**Comment by frkinta** [comment]
It look like not fixed in `TTemplate` class in `pradolite.php` file

**Comment by ctrlaltca** [comment]
Updated in 5dd4b52e6068294001d0669eebb88ac8e3481a97, thank you
