### ISSUE TITLE
TLinkButton "CausesValidation" not working

### ISSUE THREAD

**Issue by zendre4** [pradosoft/prado#629]
Hello,

I try to use the component "TLinkButton" without page validation (refresh) but it's not working .

I try to set "CausesValidation" to false but the page alwas refresh...

**Comment by ctrlaltca** [comment]
Hi,
  if you click a TLinkButton the page will always refresh, since clicking it will cause an http POST.
`CausesValidation=false` wiLl only prevent the link from triggering any validator present in the page.

Take page http://pradoframework.net/demos/quickstart/?page=Controls.Samples.TLinkButton.Home as an example: the first four links will always refresh the page when clicked; the fifth link will cause the validator to trigger; if you set `CausesValidation=false` on the fifth link, you will avoid it from triggering the validator.

If you want a TLinkButton-like control that doesn't cause the page to reload, try [TActiveLinkButton](http://pradoframework.net/demos/quickstart/?page=ActiveControls.ActiveLinkButton), that uses AJAX instead of POST requests.

**Comment by LCSKJ** [comment]
not sure if it works since i can't test it at home, but you may try disabling client script and set button type to button instead of submit
~~~xml
<com:TButton ButtonType="Button" EnableClientScript="false" Text="Do not POST" />
~~~

**Comment by zendre4** [comment]
It's work with TActiveLinkButton Thanks !
