### ISSUE TITLE
Callback don't work on ActiveButton used with <prop:ClientSide ... >

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#646]
Hello guys,
I'm trying using that piece of code. 

```HTML
<com:TActiveButton CssClass="btn btn-success" Text="Check domain" OnCallback="showExistDomain">
    <prop:ClientSide OnLoading="Element.show('alertnewdomain')" OnComplete="Element.hide('alertnewdomain')" />
</com:TActiveButton>
<div class="alert alert-warning" style="display:none" id="alertnewdomain">Checking ...</div>
```
When I click the button, `OnCallback` is not executed. Instead, page just refresh as `OnClick` is empty. (if set, `OnClick` is executed ) But, when I remove the `<prop:ClientSide...>` it work well.

**Comment by LCSKJ** [comment]
Which version of Prado are you using?

Since `Element.show` and `Element.hide` are functions of Prototype it looks like you are using an outdated Prado v3.2.x or lower, but looking at your CSS classes, `btn btn-success` and `alert alert-warning` are looking like Bootstrap classes which is using jQuery (used by Prado from v3.3.x up). Although it is possible to use both JS frameworks aside, that might also be the problem.

I just tested your code snippet in a Prado v3.2.x setup, it worked as expected.

Using Prado v3.3.x and changing
`OnLoading="Element.show('alertnewdomain')"` to `OnLoading="$('#alertnewdomain').show()"`
and
`OnComplete="Element.hide('alertnewdomain')"` to `OnComplete="$('#alertnewdomain').hide()"`
also worked as expected.

If the whole page refreshes after button click and is not making an ajax request, there is most likely a JS error somewhere on your page causing the button to fall back to postback instead of callback. Hit F12 and check console for any error during page load or directly after you hit the button - maybe check "pause on exceptions" if it's refreshing too fast.

**Comment by frkinta** [comment]
Thank you. 
Work using `OnLoading="$('#alertnewdomain').show()"`. I'm using Pradov3.3.2

Please the code on this page may be change http://www.pradoframework.net/demos/quickstart/?page=ActiveControls.Introduction

**Comment by ctrlaltca** [comment]
Nice catch, thank you!
Fixed in https://github.com/pradosoft/prado-demos/commit/1dec6180fa9658c9e4b2775b84e657b478afbcee
