### ISSUE TITLE
Prado 4.0 : Pradolite is missing

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#650]
Hello,

i have tried new version 4.0, why pradolite is disappeared?

**Comment by ctrlaltca** [comment]
Because you don't need anymore to include prado.php or pradolite.php, since autoloading is handled by composer. An introduction to Prado 4 is available here: http://pradoframework.net/demos/quickstart/?page=GettingStarted.Upgrading33
Please remember that Prado4 is not official yet, so things may change.

**Comment by mrizkir** [comment]
Ok thankyou.
