### ISSUE TITLE
session start issue

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#653]
Hello!
I notice that error many time in my log files

```html 
[Error] [System.TApplication] [Warning] session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' (@line 140 in file ...path...\framework33x2\Web\THttpSession.php).
```

My application.xml configuration
```xml
<module id="session" class="THttpSession" SessionName="SSID" SavePath="./protected/tmp" CookieMode="Allow" UseCustomStorage="false" AutoStart="true" GCProbability="1" UseTransparentSessionID="true" TimeOut="3600" />
```

 - PHP 5.6.31
 - Windows Server 2008 R2

**Comment by frkinta** [comment]
May this link help?

https://stackoverflow.com/questions/32898857/session-start-issues-regarding-illegal-characters-empty-session-id-and-failed

**Comment by ctrlaltca** [comment]
First, sorry for the delay.
As far as i understand you are getting errors in the server log because of malformed session ids; these ids are injected by malicious users in cookies, or potentially via url links, since UseTransparentSessionID is enabled.

I can see 4 ways to deal with this:
 1. suppress the error, eg. using @ session_start(); con: we won't get any other error message related to sessions;
 2. check if the session id is well-formed before starting the session and regenerate it; it will avoid the error, but it's quite useless, since we already know the session is broken;
 3. check if the session id is well-formed before starting the session and don't start the session if it does;
 4. ignore the error at all; since it doesn't affect normal users, we know that seeing the error on the log means then someone is borking with our server.

I'm unsure if the 3rd solution is preferable to the 4th, since it's basically "muting the problem".

**Comment by frkinta** [comment]
Choosed the 4th. thanks
