### ISSUE TITLE
ToggleButton is missing  (since 3.3.3)

### ISSUE THREAD

**Issue by jo49bimpf** [pradosoft/prado#680]
Hello,

I'nve updatetd from 3.2.4 to 3.3.3 and now the ToggleButton is missing.
I get this error:

ReferenceError: Class is not defined
	Prado.WebUI.ToggleButton = Class.create();

But I can't find any hint, that this control is removed or depreciated.

Thanks and best regards
Jürgen

**Comment by jo49bimpf** [comment]
I solved this with this little jQuery:

jQuery("#ctl0_Main_ctl0").click(function() {jQuery("#togglePanel").toggle();});

**Comment by ctrlaltca** [comment]
`Prado.WebUI.ToggleButton` never existed inside the PRADO Framework. It was probably a javascript object created inside your application.
Since 3.3 moved from prototype.js to jQuery, the `Class` javascript object is not available anymore.
I suggest you to read http://pradoframework.net/demos/quickstart/?page=GettingStarted.Upgrading32 for other possible problems you can find while upgrading from 3.2 to 3.3.
