### ISSUE TITLE
NTLM Single Sign On support?

### ISSUE THREAD

**Issue by jmartens** [pradosoft/prado#730]
Does Prado have a solution to use single sign on on Windows using a proxy server in front off the application?

For instance using Apache and mod_auth_ntlm (https://github.com/TQsoft-GmbH/mod_authn_ntlm)?

**Comment by ctrlaltca** [comment]
Hello, no solution is currently implemented for NTLM authentication.
If you plan to use mod_authn_ntlm, you'll probably won't even need one, since the user details will be handled by Apache and available in php's $_SERVER superglobal. Still, you will have about no control on user logins/logouts, since they will be totally handled by the Apache module.
If you take a look at packagist you'll find a lot of packages re-implementing NTLM authentication in pure php. I would start with picking one of them and implement a new IUserManager that uses that library to authenticate users.
An example of such an implementation is available here: https://github.com/pradosoft/prado-demos/blob/master/blog/protected/Common/BlogUserManager.php

**Comment by ctrlaltca** [comment]
Closing this issue; feel free to reopen if you need to further discuss this.
By the way, did you get it working?
