### ISSUE TITLE
THTML & TBody Web Controls needed for their TWebControlDecorators

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#734]
In light of the TWebControlDecorator feature, It makes a lot more sense for Themes to control the html and body tags, and their surrounding decoration, now than it did before this feature.

It also provides a more consistent framework.

TPage should probably encode the THTML and TBody tags like it does the THead, for being singletons.

**Comment by belisoful** [comment]
I have this coded up.  It just needs to be integrated, tested and uploaded.

**Comment by belisoful** [comment]
Looking through the code. THead is subclassed from TControl.  HTML and Body can get the full treatment of html tags, css, style, lang, etc.  THead is extremely specialized, but TBody and THTML are not as specific.

Is there any discussion as to whether the TBody and THTML should be children of TWebControl or THtmlElement?

**Comment by ctrlaltca** [comment]
Looks like `TBody` can just be a `THtmlElement` with `TagName=body`.
I never needed it, but i guess it won't hurt to let people have a choice of using it.

I'm unsure if a THtml element really makes sense, since it would have only a few usable attributes (lang being the only one actually useful); I'll be glad to change my mind if you show me a possible use of this tag.

About decorators on html and body tags, right now i always used one (or more) master layout where i can just write plain html, but again maybe it's just me being used to this way and not realizing what you mean. So, i'd like to see what you are working on, once you are ready

**Comment by belisoful** [comment]
My thoughts are that THTML and TBody could have surrounding supporting html code moved to the theme through Web Decorators.  Having the Theme embed the <!DOCTYPE html>, and having programmable lang could be proper for multi-language sites and in case people want to have a different DocType on mobile devices where mobile devices use different themes than normal.  The theme could supply the doctype with THTML decorators.   Also a TBody would have decorators for any extra supporting html being from the theme.

THTML may need special treatment due to its limitations.  maybe link the lang attribute to the localization?  Only PreTagText Web Decorator would be needed.  TBody would only need the PreContentsText, PreContentsTemplate, PostContentsTemplate, and PostContentsText elements of the Web Decorator.

I don't know if this is worth it...  yet.   having this discussion is helpful to think about it.

**Comment by belisoful** [comment]
Having a TBody would be helpful in the use case of a module adding controls and html/text at the beginning or end of the contents of the body.  I'm working on a module for Cookie tracking consent and the TBody would be helpful for standardization.

**Comment by belisoful** [comment]
I've been analyzing this, and I'm still on the fence myself.

**Comment by belisoful** [comment]
Anyone else have any comments?  I'm thinking of closing this issue.

**Comment by belisoful** [comment]
thank you for helping me and us thinking about this issue.  Closed.
