### ISSUE TITLE
Branch issues

### ISSUE THREAD

**Issue by ctrlaltca** [pradosoft/prado#854]
@belisoful there's some issues with branches.
Prado always used the "master" branch
I saw a new "main" branch appeared, and some PRs were targeting "main" instead of "master"
When i merged #850, it went first into "main" and then i had to pull it to "master", too.
Once merged to "master", i got the option to delete "main" and did it.
This unfortunately caused the automatic closing of #849, #842 and #837 (@zendre4)
Let me check if i can restore them, but is is probably going to cause issues if you plan to add more commits to those PRs.

**Comment by belisoful** [comment]
that was a mistake on my own branch.  the Github app did an accidental commit of changes already committed??  as I was trying update my on branch to prado/master.  so I was trying to reset my master.  I was goofing around with renaming branches.

I need to reset my Prado branch entirely on the latest.  it's entirely ok.  no worries.  i should reset those branches anyway...  so you actually helped me.  🧚

**Comment by ctrlaltca** [comment]
I just retargeted the existing PRs on master
If they are ok i can go on with the review and pull them

**Comment by belisoful** [comment]
Yes please.

**Comment by belisoful** [comment]
I didn't know they were not properly targeted, or that targets could be changed.   hmmm.   GitHub learning.

**Comment by belisoful** [comment]
Did I accidentally affect a Prado branches?  I was thinking of having an experimental branch on my own account so people could follow and comment without affecting my own master.  What to call it? main?  experimental? default?  sigh.  It likely wouldn't pass all the unit tests due to being experimental   Changes would be ported over my master branch (or subbranch for merging on master) and would pass the tests.  I was doing what I could to keep it on my own branch.  Did it not stay on my own branch?

**Comment by belisoful** [comment]
How exactly my own branch mistakes affected Prado's master issues is really beyond me.  hmm.  GitHub: isn't that what our own account branches are for?  making our own mistakes without affecting master?

**Comment by ctrlaltca** [comment]
I'm not sure how this happened. No need to worry anyway.
