### ISSUE TITLE
Files permissions created by Prado

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#865]
Hi,

Is there any particular reason to have set the default permissions to 0777 for the PRADO_CHMOD constant? I think that for security reasons it would be better to have the value at 0755.

Shouldn't there be two constants, one for files at 0644 (PRADO_FILE_CHMOD) and one for directories (PRADO_DIR_CHMOD) at 0755? There is no reason to put execution rights on files.

Jean-Luc

**Comment by ctrlaltca** [comment]
As far as i know it was supposed to be used for directories like protected/runtime/* and assets/*, but it looks like it's now used also for some automatically-generated files (localization and minified js).
I agree they should be separated for files and directories, and that default values should be stricter.
Replacing/renaming PRADO_CHMOD would be a backward-incompatible change, since it's meant to be defined by users in index.php. To be honest i never saw a single project overriding that value, probably because it was so large it never caused access problems to anyone.

**Comment by majuca** [comment]
I think we can modify the code without making big changes and remain retro-compatible. We could modify the function getDefaultPermisssions like this:

**Comment by majuca** [comment]
I think we can modify the code without making big changes and remain retro-compatible. We could modify the function getDefaultPermisssions like this:

```
public static function getDefaultPermissions(bool isDir = false): int
{
        if (defined('PRADO_DIR_CHMOD') && isDir ) {
             return PRADO_DIR_CHMOD;
        }
        if (defined('PRADO_FILE_CHMOD') && !isDir ) {
             return PRADO_FILE_CHMOD;
        }
	return PRADO_CHMOD;
}
```
If we don't define PRADO_DIR_CHMOD or PRADO_FILE_CHMOD, the application continue to work as brefore. If we want to change the permissions for the files differently than the directories, we just have to add the defines in the index.php.

So where we call the function chmod just after a mkdir, we should call getDefaultPermissions(true). If you are agree with this, I could propose a PR.

**Comment by ctrlaltca** [comment]
I'd think to have two new methods getDefaultFilePermission() and getDefaultDirPermission() using the new constants, make the old getDefaultPermissions() point to getDefaultDirPermission() and mark it deprecated, so we can remove it in the next major. But whichever is good for you is well accepted, too. Go on with the PR please.

**Comment by majuca** [comment]
ok, I will do it!
